import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navibar from './components/shared/Navibar/Navibar';
import Footer from './components/shared/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navibar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
